zuul:
  routes:
    api-a.path: /spoapi/**
    api-a.serviceId: spoapp
ribbon:
  eureka:
    enabled: true
#spoapp:
#  ribbon:
#    DeploymentContextBasedVipAddresses: spoapp
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ReadTimeout: 50000
#    MaxAutoRetries: 2
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 30000 #缺省为1000   
spring:
  application:
    name: eureka-server
    profiles: peer2
server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: @eureka_ip1@
  instance:
    prefer-ip-address: true 
    hostname: peer2
  server:
    evictionIntervalTimerInMs: 5000       
    renewalPercentThreshold: 0.3