#spoapp:
#  ribbon:
#    DeploymentContextBasedVipAddresses: spoapp
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ReadTimeout: 50000
#    MaxAutoRetries: 2
#uaa:
#  ribbon:
#    DeploymentContextBasedVipAddresses: uaa
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ReadTimeout: 50000
#    MaxAutoRetries: 2
#wip:
#  ribbon:
#    DeploymentContextBasedVipAddresses: wip
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ReadTimeout: 50000
#    MaxAutoRetries: 2
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 30000 #缺省为1000     
ribbon:
  eureka:
    enabled: true
users:
  ribbon:
    listOfServers: localhost:8889
eureka:
  client:
    serviceUrl.defaultZone: @eureka_ip1@,@eureka_ip2@
    fetchRegistry: true
  instance:
    prefer-ip-address: true 
spring:
  application:
    name: ui
zuul:
  routes:
    api-a:
      path: /spoapi/**
      serviceId: spoapp
    api-b:
      path: /uaaapi/**
      serviceId: uaa
    api-c: 
      path: /wip/**
      serviceId: wip
server:
  port: 8085
