server:
   port: 8080
spring:
    jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      show-sql: false
      hibernate:
       ddl-auto: update
       naming:
         implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
       properties:
         hibernate: 
           format_sql: true
    redis: 
      database: 1
      host: 192.168.0.12
      port: 6379
      password: 
      pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
         timeout: 0
    application:
      name: wip