server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.5.193:8761/eureka/
    fetchRegistry: true
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:sqlserver://10.1.5.190:1433;DatabaseName=soadb
    username: sa
    password: Qazx1234
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        ddl-auto: none
        default_schema: PR_Integration
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456
    pool:
      max-active: -1
      max-wait: -1
      max-idle: -1
      min-idle: -1
      timeout: 0
  application:
    name: wip
  rabbitmq:
    host: 10.1.5.193
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  data:
    mongodb:
      uri: mongodb://10.1.5.193:27017/test
custom:
  archive:
    beannames: C2H2,Ccf,Ctg,ExCar,InCar,Preox,Temper,Tunnel,Wash