spring:
  application:
    name: ui
  cloud:
    config:
      profile: dev
      config: 
        label: master
        uri: http://localhost:8888/
eureka:
  client:
    serviceUrl.defaultZone: @eureka_ip1@,@eureka_ip2@
    fetchRegistry: true
  instance:
    prefer-ip-address: true 
