eureka:
  instance:
    hostname: eurekaserverslaver
  client:
    serviceUrl:
      defaultZone: http://10.1.5.193:8761/eureka/
    fetchRegistry: false
    register-with-eureka: false
  server: 
    enableSelfPreservation: false
server:
  port: 8762