eureka:
  instance:
    hostname: eurekaserverslaver
  client:
    serviceUrl:
      defaultZone: http://localhost:8886/eureka/
    fetchRegistry: false
  server: 
    enableSelfPreservation: false
server:
  port: 8887