spring:
  application:
    name: schedule-ps
  datasource:
    url: jdbc:sqlserver://10.1.5.190:1433;DatabaseName=soadb
    username: sa
    password: Qazx1234
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.5.193:8761/eureka/
    fetchRegistry: true
  instance:
    prefer-ip-address: true
server:
  port: 8082

  