package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.resource_type
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.resouce_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date validFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date validTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Boolean isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.create_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.create_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.last_update_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_resource.last_update_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date lastUpdateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.id
     *
     * @return the value of public.spo_resource.id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.id
     *
     * @param id the value for public.spo_resource.id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.resource_type
     *
     * @return the value of public.spo_resource.resource_type
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.resource_type
     *
     * @param resourceType the value for public.spo_resource.resource_type
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.resouce_id
     *
     * @return the value of public.spo_resource.resouce_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.resouce_id
     *
     * @param resouceId the value for public.spo_resource.resouce_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.valid_from
     *
     * @return the value of public.spo_resource.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.valid_from
     *
     * @param validFrom the value for public.spo_resource.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.valid_to
     *
     * @return the value of public.spo_resource.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getValidTo() {
        return validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.valid_to
     *
     * @param validTo the value for public.spo_resource.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.isactive
     *
     * @return the value of public.spo_resource.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Boolean getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.isactive
     *
     * @param isactive the value for public.spo_resource.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.create_by
     *
     * @return the value of public.spo_resource.create_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.create_by
     *
     * @param createBy the value for public.spo_resource.create_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.create_on
     *
     * @return the value of public.spo_resource.create_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.create_on
     *
     * @param createOn the value for public.spo_resource.create_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.last_update_by
     *
     * @return the value of public.spo_resource.last_update_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.last_update_by
     *
     * @param lastUpdateBy the value for public.spo_resource.last_update_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_resource.last_update_on
     *
     * @return the value of public.spo_resource.last_update_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getLastUpdateOn() {
        return lastUpdateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_resource.last_update_on
     *
     * @param lastUpdateOn the value for public.spo_resource.last_update_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setLastUpdateOn(Date lastUpdateOn) {
        this.lastUpdateOn = lastUpdateOn;
    }
}