package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

import com.ge.digital.spo.chain.infrastructure.common.ModelBase;

public class RoleResource extends ModelBase{


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_role_resource.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String resourceId;

  

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rel_role_resource.role_id
     *
     * @return the value of public.rel_role_resource.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rel_role_resource.role_id
     *
     * @param roleId the value for public.rel_role_resource.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rel_role_resource.resource_id
     *
     * @return the value of public.rel_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rel_role_resource.resource_id
     *
     * @param resourceId the value for public.rel_role_resource.resource_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    
}