package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

import com.ge.digital.spo.chain.infrastructure.common.ModelBase;

public class RoleGroup extends ModelBase{
    

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_role_group.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_role_group.group_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String groupId;

    

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rel_role_group.role_id
     *
     * @return the value of public.rel_role_group.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rel_role_group.role_id
     *
     * @param roleId the value for public.rel_role_group.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rel_role_group.group_id
     *
     * @return the value of public.rel_role_group.group_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rel_role_group.group_id
     *
     * @param groupId the value for public.rel_role_group.group_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }
}