package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

import com.ge.digital.spo.chain.infrastructure.common.ModelBase;

public class Role extends ModelBase{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.role_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.role_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.role_description
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String roleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date validFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date validTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Boolean isactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_role.role_type
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String roleType;


    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.role_id
     *
     * @return the value of public.spo_role.role_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.role_id
     *
     * @param roleId the value for public.spo_role.role_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.role_name
     *
     * @return the value of public.spo_role.role_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.role_name
     *
     * @param roleName the value for public.spo_role.role_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.role_description
     *
     * @return the value of public.spo_role.role_description
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.role_description
     *
     * @param roleDescription the value for public.spo_role.role_description
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.valid_from
     *
     * @return the value of public.spo_role.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.valid_from
     *
     * @param validFrom the value for public.spo_role.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.valid_to
     *
     * @return the value of public.spo_role.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getValidTo() {
        return validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.valid_to
     *
     * @param validTo the value for public.spo_role.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.isactive
     *
     * @return the value of public.spo_role.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Boolean getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.isactive
     *
     * @param isactive the value for public.spo_role.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_role.role_type
     *
     * @return the value of public.spo_role.role_type
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_role.role_type
     *
     * @param roleType the value for public.spo_role.role_type
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

}