package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

import com.ge.digital.spo.chain.infrastructure.common.ModelBase;

public class UserGroup extends ModelBase{


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_user_group.user_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_user_group.group_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String groupId;

    

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rel_user_group.user_id
     *
     * @return the value of public.rel_user_group.user_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rel_user_group.user_id
     *
     * @param userId the value for public.rel_user_group.user_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rel_user_group.group_id
     *
     * @return the value of public.rel_user_group.group_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rel_user_group.group_id
     *
     * @param groupId the value for public.rel_user_group.group_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

   
}