package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

import com.ge.digital.spo.chain.infrastructure.common.ModelBase;

public class User extends ModelBase{


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.login_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.password
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.first_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.last_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date validFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Date validTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.spo_user.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private Boolean isactive;

    private String locale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.id
     *
     * @return the value of public.spo_user.id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    private String defaultNetGrp;
    public String getDefaultNetGrp() {
		return defaultNetGrp;
	}

	public void setDefaultNetGrp(String defaultNetGrp) {
		this.defaultNetGrp = defaultNetGrp;
	}

	public String getLandingPage() {
		return landingPage;
	}

	public void setLandingPage(String landingPage) {
		this.landingPage = landingPage;
	}

	private String landingPage;
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.id
     *
     * @param id the value for public.spo_user.id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.login_id
     *
     * @return the value of public.spo_user.login_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.login_id
     *
     * @param loginId the value for public.spo_user.login_id
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.password
     *
     * @return the value of public.spo_user.password
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.password
     *
     * @param password the value for public.spo_user.password
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.first_name
     *
     * @return the value of public.spo_user.first_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.first_name
     *
     * @param firstName the value for public.spo_user.first_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.last_name
     *
     * @return the value of public.spo_user.last_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.last_name
     *
     * @param lastName the value for public.spo_user.last_name
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.valid_from
     *
     * @return the value of public.spo_user.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.valid_from
     *
     * @param validFrom the value for public.spo_user.valid_from
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.valid_to
     *
     * @return the value of public.spo_user.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getValidTo() {
        return validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.valid_to
     *
     * @param validTo the value for public.spo_user.valid_to
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.isactive
     *
     * @return the value of public.spo_user.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Boolean getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.isactive
     *
     * @param isactive the value for public.spo_user.isactive
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.create_by
     *
     * @return the value of public.spo_user.create_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.create_by
     *
     * @param createBy the value for public.spo_user.create_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.create_on
     *
     * @return the value of public.spo_user.create_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.create_on
     *
     * @param createOn the value for public.spo_user.create_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.last_update_by
     *
     * @return the value of public.spo_user.last_update_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.last_update_by
     *
     * @param lastUpdateBy the value for public.spo_user.last_update_by
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.spo_user.last_update_on
     *
     * @return the value of public.spo_user.last_update_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public Date getLastUpdateOn() {
        return lastUpdateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.spo_user.last_update_on
     *
     * @param lastUpdateOn the value for public.spo_user.last_update_on
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    public void setLastUpdateOn(Date lastUpdateOn) {
        this.lastUpdateOn = lastUpdateOn;
    }

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}
    
}