package com.ge.digital.spo.chain.infrastructure.user.model;

import java.util.Date;

import com.ge.digital.spo.chain.infrastructure.common.ModelBase;

public class UserRole extends ModelBase{


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_user_role.role_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rel_user_role.user_id
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    private String userId;

    

    public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}