package com.ge.digital.spo.security.service;

import java.util.List;

import com.ge.digital.spo.chain.infrastructure.user.model.UserRole;

public interface UserRoleService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    UserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKey(UserRole record);
    
    List<UserRole> selectByRoleId(String roleId);
    
    List<UserRole> selectByUserId(String userId);
}
