eureka:
  client:
    serviceUrl.defaultZone: @eureka_ip1@,@eureka_ip2@
    fetchRegistry: true
  instance:
    prefer-ip-address: true
turbine:
  appConfig: wip
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")    