package com.ge.digital.schedule.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "biz_auto_incr")
public class BizAutoIncr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_biz_auto_incr.id
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	@Column(name = "id")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_biz_auto_incr.biz_key
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
	@Column(name = "bizKey")
    private String bizKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_biz_auto_incr.value
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
	@Column(name = "value")
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_biz_auto_incr.id
     *
     * @return the value of public.sys_biz_auto_incr.id
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_biz_auto_incr.id
     *
     * @param id the value for public.sys_biz_auto_incr.id
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_biz_auto_incr.biz_key
     *
     * @return the value of public.sys_biz_auto_incr.biz_key
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public String getBizKey() {
        return bizKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_biz_auto_incr.biz_key
     *
     * @param bizKey the value for public.sys_biz_auto_incr.biz_key
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public void setBizKey(String bizKey) {
        this.bizKey = bizKey == null ? null : bizKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_biz_auto_incr.value
     *
     * @return the value of public.sys_biz_auto_incr.value
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_biz_auto_incr.value
     *
     * @param value the value for public.sys_biz_auto_incr.value
     *
     * @mbg.generated Tue Jun 20 10:37:49 CST 2017
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}