eureka:
  instance:
    hostname: eurekaserver
  client:
    serviceUrl:
      defaultZone: http://10.1.4.24:8762/eureka/
    fetchRegistry: false
  server: 
    enableSelfPreservation: false
server:
  port: 8761