eureka:
  instance:
    hostname: eurekaserver
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/
    fetchRegistry: false
  server: 
    enableSelfPreservation: false
server:
  port: 8761