package com.ge.digital.spo.chain.infrastructure.user.dao;

import java.util.List;

import com.ge.digital.spo.chain.infrastructure.user.model.Resource;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_resource
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_resource
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_resource
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_resource
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    Resource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_resource
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_resource
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int updateByPrimaryKey(Resource record);
    
    // ------------------------------------------------------------ //
    
    List<Resource> selectAll();
}