

package com.ge.digital.spo.chain.infrastructure.user.dao;

import java.util.List;

import com.ge.digital.spo.chain.infrastructure.user.model.Role;
import com.ge.digital.spo.chain.infrastructure.user.vo.RoleVo;

public interface RoleMapper {
    /** 
     * This test method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_role
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_role
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_role
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_role
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_role
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_role
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int updateByPrimaryKey(Role record);
    
    List<RoleVo> findByRoleVo(RoleVo vo);
    
    Role selectByRoleId(String roleId);
    
    Role selectByRoleName(String roleName);
    
    int updateByRoleId(Role record);
    
    int updateByRoleIdSelective(Role record);
    
    List<Role> selectAll();
    
}