package com.ge.digital.spo.chain.infrastructure.user.dao;

import com.ge.digital.spo.chain.infrastructure.user.model.RoleGroup;

public interface RoleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_role_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_role_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insert(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_role_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insertSelective(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_role_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    RoleGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_role_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKeySelective(RoleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_role_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKey(RoleGroup record);
}