package com.ge.digital.spo.chain.infrastructure.user.dao;

import java.util.List;

import com.ge.digital.spo.chain.infrastructure.user.model.UserRole;
import com.ge.digital.spo.chain.infrastructure.user.vo.UserRoleVo;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int deleteByPrimaryKey(String id);
    int deleteByUserKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insert(UserRole record);
    //insertByEntity
    int insertByEntity(UserRole record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    UserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_role
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKey(UserRole record);
  
    int deleteByRoleVo(UserRoleVo vo);
    //findByUserByRoleVo
    List<UserRoleVo> findByUserRoleVo(UserRoleVo vo);
    
    List<UserRole> selectByRoleId(String roleId);
    
    List<UserRole> selectByUserId(String userId);
}