
package com.ge.digital.spo.chain.infrastructure.user.dao;

import java.util.List;

import com.ge.digital.spo.chain.infrastructure.user.model.User;
import com.ge.digital.spo.chain.infrastructure.user.vo.UserByRoleVo;
import com.ge.digital.spo.chain.infrastructure.user.vo.UserVo;

public interface UserMapper {
    /**
     * This test method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_user
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_user
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_user
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_user
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_user
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.spo_user
     *
     * @mbg.generated Thu Sep 21 10:46:10 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    //findByUserVo
    List<UserVo> findByUserVo(UserVo vo);
    //findByUserByRoleVo
    List<UserByRoleVo> findByUserByRoleVo(UserByRoleVo vo);
    //findByUserAndRoleVo
    List<UserByRoleVo> findByUserAndRoleVo(UserByRoleVo vo);
}