package com.ge.digital.spo.chain.infrastructure.user.dao;

import com.ge.digital.spo.chain.infrastructure.user.model.UserGroup;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int insertSelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    UserGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKeySelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rel_user_group
     *
     * @mbg.generated Fri Sep 22 15:02:02 CST 2017
     */
    int updateByPrimaryKey(UserGroup record);
}